LOAD DATA LOCAL INFILE '/docker-entrypoint-initdb.d/test_bia.csv'
INTO TABLE ENERGY
FIELDS TERMINATED BY ',' LINES TERMINATED BY '\n'

(ID,
METER_ID,
ACTIVE_ENERGY,
REACTIVE_ENERGY,
CAPACITIVE_REACTIVE,
SOLAR,
@FECHA_COLUMNA) SET DATE = STR_TO_DATE(@FECHA_COLUMNA,
'%Y-%m-%d %H:%i:%s+00');