DROP TABLE IF EXISTS ENERGY;

CREATE TABLE IF NOT EXISTS ENERGY (
    ID VARCHAR(36),
    METER_ID INT,
    ACTIVE_ENERGY DOUBLE,
    REACTIVE_ENERGY DOUBLE,
    CAPACITIVE_REACTIVE DOUBLE,
    SOLAR DOUBLE,
    DATE TIMESTAMP
);